
version: '{build}'
os: Visual Studio 2019
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: 4qvxo9ONx36nPuf2u7V0J9E+l55g6gU6t1p2xp7Az04mhYv5sGeaSddllhqMFogk
install:
- ps: >-
    nuget update -self

    dotnet restore

    nuget restore packages.config -PackagesDirectory packages
    
    dotnet build .\src\PaulMiami.AspNetCore.Mvc.Recaptcha\PaulMiami.AspNetCore.Mvc.Recaptcha.csproj
build: off
test_script:
- ps: dotnet build .\sample\TestWebApp\TestWebApp.csproj
- ps: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=../../testResults/coverage.xml /p:Exclude="[PaulMiami.*Test]*" /p:Include="[PaulMiami*]*"  /p:ExcludeByAttribute="System.Diagnostics.DebuggerNonUserCodeAttribute"
- ps: ./Coverage.ps1